# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0b6a06843bce7b9e854430883fd85d3970d7be7e8c7002137a315bed9e68c9e03b779fd11c3ef5c1e6aee0ce8411b5c6fe3ef247175722e9b83864e2c86201

test:
  secret_key_base: f9061b748347b868ccbecbce56f5655d371d436cadc1bd3c607c2d7ebd63f239f2b2ade167aadcf5816ce7a3cb9d5700f488d5db6bc4d753f1fc49dcd1d7d47f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
